// monorepo-demo/packages/apps/admin/src/App.vue
<template>
  <el-container style="min-height: 100vh">
    <el-aside width="200px" style="background-color: #001529">
      <div style="color: white; padding: 16px; font-size: 18px">
        Vue Admin
      </div>
      <el-menu
        :default-active="currentRoute"
        router
        background-color="#001529"
        text-color="#fff"
        active-text-color="#ffd04b"
      >
        <el-menu-item index="/">
          <el-icon><el-icon-house /></el-icon>
          <span>Dashboard</span>
        </el-menu-item>
        <el-menu-item index="/users">
          <el-icon><el-icon-user /></el-icon>
          <span>用户管理</span>
        </el-menu-item>
      </el-menu>
    </el-aside>

    <el-container>
      <el-header style="background-color: #fff; box-shadow: 0 1px 4px rgba(0,21,41,.08)">
        <div style="display: flex; align-items: center; height: 100%">
          <h2>Monorepo Admin 后台</h2>
        </div>
      </el-header>

      <el-main>
        <router-view />
      </el-main>

      <el-footer style="text-align: center">
        Vue Admin ©{{ new Date().getFullYear() }} Created with Monorepo
      </el-footer>
    </el-container>
  </el-container>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { House as ElIconHouse, User as ElIconUser } from '@element-plus/icons-vue';

const route = useRoute();
const currentRoute = computed(() => route.path);
</script>

<style scoped>
.el-aside {
  color: #fff;
}

.el-header {
  display: flex;
  align-items: center;
  padding: 0 20px;
}

.el-main {
  background-color: #f0f2f5;
  padding: 20px;
}
</style>

// monorepo-demo/packages/apps/web-app/src/App.tsx
import React from 'react';
import { Routes, Route, Link } from 'react-router-dom';
import { Layout, Menu } from 'antd';
import { HomeOutlined, UserOutlined } from '@ant-design/icons';

import HomePage from './pages/HomePage';
import UsersPage from './pages/UsersPage';

const { Header, Content, Footer } = Layout;

const App: React.FC = () => {
  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Header style={{ display: 'flex', alignItems: 'center' }}>
        <div style={{ color: 'white', fontSize: '20px', marginRight: '50px' }}>
          React Web App
        </div>
        <Menu
          theme="dark"
          mode="horizontal"
          defaultSelectedKeys={['/']}
          items={[
            {
              key: '/',
              icon: <HomeOutlined />,
              label: <Link to="/">首页</Link>,
            },
            {
              key: '/users',
              icon: <UserOutlined />,
              label: <Link to="/users">用户列表</Link>,
            },
          ]}
        />
      </Header>
      <Content style={{ padding: '24px 50px' }}>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/users" element={<UsersPage />} />
        </Routes>
      </Content>
      <Footer style={{ textAlign: 'center' }}>
        React Web App ©{new Date().getFullYear()} Created with Monorepo
      </Footer>
    </Layout>
  );
};

export default App;
